ALTER TYPE "OfferStatus" ADD VALUE IF NOT EXISTS 'SELECTED';
ALTER TYPE "InspectionQuoteStatus" ADD VALUE IF NOT EXISTS 'SELECTED';
ALTER TYPE "TransportQuoteStatus" ADD VALUE IF NOT EXISTS 'SELECTED';
